spring:
  sql.init.mode: always
  datasource:
    username: sa
    password: Asd01020304
    jdbc-url: jdbc:sqlserver://localhost:1433;databaseName=hexagonalTransferencia;encrypt=false
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  cloud:
    openfeign:
      client:
        config:
          cadastro:
            url: http://localhost:8081/api/cadastros/
          bacen:
            url: http://localhost:8082/api/bacen/transferencia/

  redis:
    database: 0
    host: localhost
    port: 6379
    password: UmVkaXMwMTAyMDMwNA==
    timeout: 60000



build: "conta.builds.tresquatro.BuildTresEQuatro"