spring:
  datasource:
    username: sa
    password: Asd01020304
    jdbc-url: jdbc:sqlserver://localhost:1433;databaseName=hexagonalTransferenciaProd;encrypt=false
  jpa:
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: none
    show-sql: false

build: "conta.builds.tresquatro.BuildTresEQuatro"